spring:
  application:
    name: BE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.example.BE

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

ai:
  base-url: ${AI_BASE_URL}
  recommend-path: ${AI_RECOMMEND_PATH}
  pilgrimage-path: ${AI_PILGRIMAGE_PATH}
